# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://github.com/codecov/example-node

language: "node_js"
node_js:
- "6"
- "8"
install:
- "npm install"
os:
- "linux"
- "osx"
branches:
  only:
  - "master"
  - "develop"
  - /^v\d/
cache:
  directories:
  - "node_modules"
script:
- "npm run verify"
deploy:
  provider: npm
  on:
    tags: true
  email:
    secure: QMeCyzNUsI/Fz3rQUXYaxhtbn98ejy5rcZzIWA5gZq+HB/Gy8tlbrXWw5n5MIPxs53uE6krR2gls6uH6ivjFyBgfMm7CRRYGQC1y+mE6Cepzerk4ipTGTk3V4kYKoMBJnBWZVVTJrOWfKShyEJ9xtDOZ342QaAB6kkGN5qOtSTuXr5BbMB44O3aO/SF96aNaONIrzZX8lJ/baKpGCeDmo1l7FnNq1h5XppBhygFlBdEjbyRt90KDxD4nyskJSLMbyMh2QmGxptCKPuPAQ7Vm46KwqKCTP5I+lorXPnNAF9uQ1ACpJt9CZrd+B1y+QUyTJELm4Myfmd+Iw5QME5z+IqYc10q6TDOp7LuJOsFPYAM+9AXGIbyOVJzSz0QpISMO+U9qRpmQlW+IB22gLyFG3e7/jCkqm6E4UjCQCRRhSztkz0mp4/C9iFZds2WdWemUwUoKhzrXi/5gpdWEi2eCBDDfnFbG6NJ6vfCKhP25a5FWCE76U593eL8YBixwFTdHSonVKa1r+9TcVy5UI4P13mvtAoskd5wc8ZgchVRFxXj6cXn/qgJySOoblYtcoy3DseM04qk6/geFs3zMTCQdEyrWyNKAUMaU+jtLnDa01JXiKQgBrloN3ta9nTjxTUEEFYh+eqeNyarDwdnJpAMORKLRCnd6J7vksK5Lt/pEsOM=
  api_key:
    secure: R0E+jKPpgiykylDWE4Rs1SlAaYwsWuPE9YSa+7tQvH0sZZuLTtY/77IN/X+cgGrTs4FGE8NT5WleyG5/mtZOaKOiEr0BDh0c4gG34SvsEueVB4PvJH/Jb6BrkzbBX2AIco/f6yUL3NPi8JeT9UlShORf1G+3ZY37cdL7Y/yxgsgZMNLOgUTKJXJrdXJvDDo2/tuVxkCHB+SpxhFN+wH++h1ZOREoBGPbkfPNgnj7e99fqqFjajVLs46WXU016B/paKkUd7YWjq4LLnf57isnaNVMPiWhGvS8xPmacSnBBcADzhwWYbVdLi6q7XUoG0R7DpQrbEOU5hTmDRCD6nx36J7FxHhnEH4s6qxxety4YoMqz5EYPjF4HSRbKhd2lM6qs5SaTbAj9bF4QL0JspjJtbTMmsH8bfEvxeE4pWEYdJiq1fQrXQd5OsQd9ZdXw7T82fwUvSWOsVSNEEOOciFJjTVbdJBM20mNSQBVH9gOEEZNSASih3SFP/6CX1cf21nyGs5ALQrexgBamBjSM0Wd5ssnwWLw54iaJYR+vFtWtmcGvJ6WRMhFyV/lxfEV4H3mEyC5j8JRC7IdtZwpZ3gj2duyT8iOEL25JRhA+CaZPNn0fQcdB3VGU84W+IYE/hDwId+qCYIeqVtmeH/NGa/e86MKtjP4mK/gavP5SETFOmg=
